# Generated by Django 5.0.3 on 2024-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=99999, help_text='Order of the category cluster for sorting.'),
        ),
    ]
