# Generated by Django 5.0.3 on 2024-08-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('address_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('whatsapp', models.BigIntegerField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('open_hours', models.TextField(blank=True, null=True)),
                ('payment_methods', models.TextField(blank=True, null=True)),
                ('parking', models.CharField(blank=True, max_length=2000, null=True)),
                ('alcohol_patents', models.CharField(blank=True, max_length=2000, null=True)),
                ('website', models.CharField(blank=True, max_length=2000, null=True)),
                ('whatsapp_orders_extension', models.BooleanField(default=False)),
                ('category_clusters_extension', models.BooleanField(default=False)),
                ('price_options_extension', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_bg', models.CharField(blank=True, max_length=20, null=True)),
                ('main_color', models.CharField(blank=True, max_length=20, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
