# Generated by Django 5.0.3 on 2024-08-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttheme',
            name='bg_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
