# Generated by Django 5.0.3 on 2024-08-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycluster',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the category cluster for sorting.'),
        ),
    ]
