# Generated by Django 5.0.3 on 2024-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_clusters', '0002_categorycluster_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycluster',
            name='order',
            field=models.PositiveIntegerField(default=99999, help_text='Order of the category cluster for sorting.'),
        ),
    ]
