"""
Django settings for multimenu project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


PROJECT_DOMAIN = 'vamosresto.com'



# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	# apps
	'apps.categories',
	'apps.products',
	'apps.restaurants',
	'apps.users',
	'apps.core',
    'apps.category_clusters',
	'apps.orders',

	# libraries
	'rest_framework',
	'corsheaders',
	'storages',
	
	#auth
	# 'corsheaders',
	# 'rest_framework',
	'rest_framework_simplejwt.token_blacklist',
	'rest_framework_simplejwt',

]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	# 'users.middleware.NonpublicMiddleware',

	'corsheaders.middleware.CorsMiddleware',

]


ROOT_URLCONF = 'qrmenu_backend.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'qrmenu_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







# S3 Buckets Configuration

AWS_QUERYSTRING_AUTH = False

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL= None













# INTERNAL_IPS = [
#     # ...
#     "127.0.0.1",
#     # ...
# ]


#########################################


from datetime import timedelta

# CORS_ORIGIN_ALLOW_ALL = True

# MIDDLEWARE += [
# 	'corsheaders.middleware.CorsMiddleware',
# ]

# REST_FRAMEWORK = {
# 	 'DEFAULT_AUTHENTICATION_CLASSES': [
# 		'rest_framework_simplejwt.authentication.JWTAuthentication',
# 	  ],
# }

# SIMPLE_JWT = {
# 	#  'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
# 	#  'REFRESH_TOKEN_LIFETIME': timedelta(weeks=1),

# 	'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1),
# 	'REFRESH_TOKEN_LIFETIME': timedelta(minutes=20),

# 	'ROTATE_REFRESH_TOKENS': True,
# 	'BLACKLIST_AFTER_ROTATION': True
# }



####################
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Longest recommended duration for access tokens
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),  # Longest recommended duration for refresh tokens
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"



#
SITE_NAME = "Test Django Next.js"

DOMAIN = 'localhost:3000'


MIDDLEWARE += [

    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",

]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
	"http://localhost:5173",
	"http://localhost:5174",
	"http://localhost:5175",
    "http://localhost:8000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://(\w+\.)?vamosresto\.com$",
]

# Increase file upload size if needed
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB


# s3 config
AWS_S3_BUCKET_NAME = "qrmenu-bucket"
AWS_STORAGE_BUCKET_NAME = AWS_S3_BUCKET_NAME
AWS_S3_REGION_NAME = 'us-east-2'
AWS_DEFAULT_REGION = 'us-east-2'
HOST_PROTOCOL = 'http://'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_S3_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = 'media'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'